config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  post 'message', to: 'messages#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # mount Actioncable for websocket
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: { minimum: 3, maximum: 15}, uniqueness: { case_sensitive: false }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new()
    @messages = Message.custom_display
  end
  def create
    
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :require_user

    def create
        message = current_user.messages.build(message_params)
        if message.save
            ActionCable.server.broadcast "chatroom_channel", new_message: message_render(message)
        end 
    end

    private

    def message_params
        params.require(:message).permit(:body)
    end
    def message_render(message)
        render(partial: 'message', locals: {message: message, session: session})
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      #good
      session[:user_id] = user.id
      flash[:success] = "You are logged in"
      redirect_to root_path
    else
      #no good
      flash.now[:error] = "log in failed"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You are logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:warning] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular orange coffee icon"></i>
  Chatroom
</h2>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div id="message-container" class="ui feed">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
            <%= form_for(@message, html:{class: "ui fluid action input", role: "form"}, url: message_path, remote: true) do |f| %>
                    <%=f.text_field :body, placeholder: "your message...", class: ""%>
                    <%= f.button "Send message",class: "ui orange button" %>
            <% end %>
            </div>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui raised card chatbox">
            <div class="content">
                <div class="ui secondary vertical menu">
                    <a class="active item">
                        Account
                    </a>
                    <a class="item">
                        Settings
                    </a>
                    <div class="ui dropdown item">
                        <i class="dropdown icon"></i>
                        Display Options
                        <div class="menu">
                        <div class="header">Text Size</div>
                        <a class="item">Small</a>
                        <a class="item">Medium</a>
                        <a class="item">Large</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="ui <%= name %> message transition">
    <i class="close icon"></i>
    <div class="">
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui tiny inverted menu">
  <%= link_to "Chatroom", root_path, class: "item" %>
    
  </a>
  <a class="item">
    <i class="rocketchat large icon"></i> Messages
  </a>
  <div class="right menu">
    <% if logged_in? %>
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">
        <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
        <a class="item">Sign up</a>
      </div>
    </div>
    <% else %>
      <div class="item">
        <%= link_to "Sign in", login_path, class: "ui green button" %>
      </div>
    <% end %>
    <% if !logged_in? %>
    <div class="item">
        <div class="ui orange button">Sign Up</div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("mess.png") %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="main">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
        <em class="text-orange"><%= message.user.username %></em> : <%= message.body %>
    </div>
  </div>
</div>